# Robust Regression Engine


> The **Robust Regression Engine** project focuses on building a reliable and generalized machine learning system for predicting house prices using advanced regression techniques. The project explores multiple supervised learning algorithms including regularized linear models, tree-based regression models, and Support Vector Regression (SVR). It also emphasizes the importance of cross-validation techniques and hyperparameter tuning to improve model stability and reduce overfitting.

> The project aims to compare different regression approaches, evaluate their performance using standard regression metrics, and identify the most suitable model for real-world real estate price prediction tasks.

## Problem Statement

> A real estate analytics company currently uses a basic regression model to estimate house prices. However, the existing system suffers from issues such as **overfitting**, **poor generalization**, and **unstable predictions** across different datasets.

> As a Machine Learning Engineer, your task is to design and develop a **Robust Regression Engine** capable of producing accurate and stable house price predictions. The system must implement advanced regression techniques, apply regularization methods, utilize proper cross-validation strategies, and compare linear as well as non-linear models.

> The project will include:

- Regularization techniques such as Ridge and Lasso Regression
- Multiple Cross-Validation strategies
- Tree-Based Regression models
- Support Vector Regression (SVR)
- Hyperparameter tuning and model optimization
- Performance evaluation using regression metrics

> The final objective is to build a regression pipeline that performs well on both training and unseen datasets while minimizing overfitting and maximizing prediction accuracy.

# Part A: CONCEPTUAL FOUNDATION (THEORY)

## 1. What is Regularization in Machine Learning? Why is it needed?

Regularization is a technique used to reduce model complexity and prevent overfitting in machine learning. It adds a penalty term to the loss function so the model does not learn unnecessary patterns from training data and performs better on unseen data.

---

## 2. Difference between Ridge Regression (L2) and Lasso Regression (L1)

Ridge Regression uses L2 regularization and reduces coefficient values but does not make them exactly zero. Lasso Regression uses L1 regularization and can shrink some coefficients to zero, which helps in feature selection and reducing unnecessary features.

---

## 3. What is Cross-Validation and why is it important?

Cross-validation is a model evaluation technique used to measure how well a machine learning model generalizes to unseen data. It improves model reliability by testing the model on multiple subsets of the dataset and helps reduce overfitting.

---

## 4. Explain the following cross-validation techniques

### K-Fold Cross-Validation

The dataset is divided into K equal parts. The model is trained on K-1 folds and tested on the remaining fold. This process repeats K times, and the average performance is calculated.

### Stratified K-Fold Cross-Validation

This method maintains the same distribution of target values in every fold. In regression, target values are first converted into bins to preserve balanced data distribution across folds.

### Leave-One-Out Cross-Validation (LOOCV)

In LOOCV, one sample is used for testing while the remaining samples are used for training. This process repeats for every data point in the dataset and provides highly accurate evaluation.

### Time Series Split

Time Series Split is used for sequential or time-based data. It preserves the order of data by training on past data and testing on future data, avoiding data leakage.

---

## 5. Why are tree-based models less sensitive to feature scaling?

Tree-based models split data based on feature values and conditions instead of distance calculations. Because of this, scaling or normalization of features does not significantly affect the performance of Decision Trees or Random Forest models.

# PART B: DATASET UNDERSTANDING & PREPARATION

# Dataset Understanding

| Feature Name | Description |
|---|---|
| property_id | Unique property ID |
| sale_date | Property sale date |
| area_sqft | Property area in square feet |
| bedrooms | Number of bedrooms |
| bathrooms | Number of bathrooms |
| location_score | Location quality score |
| property_age | Age of property |
| distance_city_km | Distance from city |
| near_school | Nearby school availability |
| near_metro | Nearby metro availability |
| crime_rate_index | Crime rate score |
| house_price_inr | Target variable (House Price) |

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_excel("HousePrice_Dataset_3800.xlsx")

In [3]:
print(df.head().to_string())

   property_id  sale_date  area_sqft  bedrooms  bathrooms  location_score  property_age  distance_city_km  near_school  near_metro  crime_rate_index  house_price_inr
0       200001 2014-01-01       2181         6          4             8.1            21               3.8            0           0              4.84         35154898
1       200002 2019-12-01       2383         5          4             5.3            28              10.9            1           1              2.89         26710893
2       200003 2016-10-01       1047         3          3             5.9             7              27.5            0           1              4.04         11216242
3       200004 2013-03-01       1753         4          3             7.0            27              12.1            0           0              3.28         21984310
4       200005 2013-07-01       1728         4          4            10.0            32               1.4            0           1              3.84         25080429

In [4]:
print("\n Dataset Shape : ",df.shape)

 Dataset Shape :  (3800, 12)

In [5]:
print("\nColumns Names :")
print(df.columns)

Columns Names :
Index(['property_id', 'sale_date', 'area_sqft', 'bedrooms', 'bathrooms',
       'location_score', 'property_age', 'distance_city_km', 'near_school',
       'near_metro', 'crime_rate_index', 'house_price_inr'],
      dtype='object')

In [6]:
df['sale_date'] = pd.to_datetime(df['sale_date'])

df['sale_year'] = df['sale_date'].dt.year
df['sale_month'] = df['sale_date'].dt.month

In [7]:
df.drop('sale_date', axis=1, inplace=True)

### 6. Identify Features and Target Variable

In [8]:
# property_id is a unique serial number with no predictive value — removed
X = df.drop(["house_price_inr", "property_id"], axis=1)
X.head(5)

,area_sqft,bedrooms,bathrooms,location_score,property_age,distance_city_km,near_school,near_metro,crime_rate_index,sale_year,sale_month
0,2181,6,4,8.1,21,3.8,0,0,4.84,2014,1
1,2383,5,4,5.3,28,10.9,1,1,2.89,2019,12
2,1047,3,3,5.9,7,27.5,0,1,4.04,2016,10
3,1753,4,3,7.0,27,12.1,0,0,3.28,2013,3
4,1728,4,4,10.0,32,1.4,0,1,3.84,2013,7

In [9]:
y = df['house_price_inr']
y.head(5)

0    35154898
1    26710893
2    11216242
3    21984310
4    25080429
Name: house_price_inr, dtype: int64

In [10]:
print("Featues Shape : ", X.shape)
print("Target Shape : ",y.shape)

Featues Shape :  (3800, 11)
Target Shape :  (3800,)

### 7. Perform Train-Test Split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("\n Training Features Shape: ", X_train.shape)
print("Testing Features Shape: ",X_test.shape)

 Training Features Shape:  (3040, 11)
Testing Features Shape:  (760, 11)

### 8. Apply Basic Preprocessing

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train) 
X_test_scaled = scaler.transform(X_test)
print("Feature scaling applied successfully. !")

Feature scaling applied successfully. !

In [13]:
X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns
)

# Also convert X_test_scaled to DataFrame for consistency
X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns
)

X_train_scaled.head(5)

,area_sqft,bedrooms,bathrooms,location_score,property_age,distance_city_km,near_school,near_metro,crime_rate_index,sale_year,sale_month
0,1.285121,1.888790,2.705537,-0.350289,0.442044,-0.289519,-1.101144,1.055484,1.512038,1.131746,1.312183
1,-1.376348,-1.795235,-1.687601,1.086406,0.279914,-0.961041,0.908146,1.055484,0.103930,-0.856412,1.601517
2,-0.036200,0.415180,-0.808973,0.626663,-0.936061,-1.846229,-1.101144,-0.947432,0.201377,-0.110853,1.601517
3,0.119552,-1.058430,-0.808973,1.316277,-0.936061,-1.327326,0.908146,-0.947432,0.157526,0.883226,0.733517
4,-0.992959,-1.058430,0.069654,0.741599,-1.017126,0.885645,-1.101144,1.055484,0.927357,-0.359373,0.154850

# PART C: REGULARIZED LINEAR MODELS

In [14]:
from sklearn.linear_model import Ridge, Lasso
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error,r2_score

### 9. Implement Ridge Regression (L2)

In [15]:
ridge_model = Ridge(alpha=1)

ridge_model.fit(X_train_scaled, y_train)

Ridge(alpha=1)

In [16]:
ridge_pred_train = ridge_model.predict(X_train_scaled)
ridge_pred_test = ridge_model.predict(X_test_scaled)

In [17]:
# Training Error
ridge_train_mse = mean_squared_error(y_train, ridge_pred_train)
print("Ridge Train Error : ",ridge_train_mse)

Ridge Train Error :  6162302702017.451

In [18]:
#Validation Error :
ridge_test_mse = mean_squared_error(y_test, ridge_pred_test)
print("Ridge Validation Error : ", ridge_test_mse)

Ridge Validation Error :  6451358176619.913

In [19]:
print("Ridge R2 Score : ", r2_score(y_test, ridge_pred_test))

Ridge R2 Score :  0.9198939018648887

## Interpretation:

> The Ridge model R2 score is around 0.92, which means the model predicts house prices with high accuracy.
> Training and validation errors are close, which shows the model generalizes well without overfitting.

### 10. Implement Lasso Regression (L1)

In [20]:
# Using alpha=0.001 because house prices are in crore range (large values)
# alpha=1 is too small to apply any regularization at this scale
lasso_model = Lasso(alpha=0.001)
lasso_model.fit(X_train_scaled, y_train)

Lasso(alpha=0.001)

In [21]:
lasso_pred_train = lasso_model.predict(X_train_scaled)
lasso_pred_test = lasso_model.predict(X_test_scaled)

In [22]:
# Lasso Training Error
lasso_train_mse = mean_squared_error(y_train, lasso_pred_train)
print("Lasso train Error : ", lasso_train_mse)

Lasso train Error :  6162283850258.384

In [23]:
# Lasso Validation Error
lasso_test_mse = mean_squared_error(y_test, lasso_pred_test)
print("Lasso Validation Error : ", lasso_test_mse)

Lasso Validation Error :  6450121508193.721

In [24]:
# Lasso R2 Scores
print("Lasso R2 Scores : ",
     r2_score(
         y_test,
         lasso_pred_test
     ))

Lasso R2 Scores :  0.9199092574969273

## Interpretation:
> The Lasso model R2 score is around 0.92, which means it predicts house prices with high accuracy.
> Lasso can shrink some feature coefficients to zero, which helps in selecting only the important features.

### 11. Tune the regularization parameter (a) using cross-validation.

### --- Ridge Hyperparameter Tuning ---

In [25]:
ridge_parameters = {
    'alpha': [0.001, 0.01, 0.1, 1, 10, 100]
}
ridge_grid = GridSearchCV(estimator = Ridge(), 
                         param_grid = ridge_parameters,
                         cv = 5, 
                         scoring = 'neg_mean_squared_error')
ridge_grid.fit(X_train_scaled, y_train)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]},
             scoring='neg_mean_squared_error')

In [26]:
print("Best Ridge Alpha : ", ridge_grid.best_params_)

Best Ridge Alpha :  {'alpha': 1}

In [27]:
best_ridge = ridge_grid.best_estimator_
best_ridge

Ridge(alpha=1)

In [28]:
best_ridge_predictions = best_ridge.predict(X_test_scaled)

In [29]:
best_ridge_mse = mean_squared_error(y_test, best_ridge_predictions)
print(
"Best Ridge Test Error : ",
best_ridge_mse
)

Best Ridge Test Error :  6451358176619.913

### --- Lasso Hyperparameter Tuning ---

In [30]:
lasso_parameters = {
    'alpha' : [0.0001, 0.001, 0.01, 0.1, 1, 10]
}

In [31]:
lasso_grid = GridSearchCV(
    estimator = Lasso(),
    param_grid = lasso_parameters,
    cv = 5, 
    scoring = 'neg_mean_squared_error'    
)

In [32]:
lasso_grid.fit(X_train_scaled, y_train)
lasso_grid

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [0.0001, 0.001, 0.01, 0.1, 1, 10]},
             scoring='neg_mean_squared_error')

In [33]:
print("Best Lasso Alpha : ", lasso_grid.best_params_)

Best Lasso Alpha :  {'alpha': 10}

In [34]:
best_lasso = lasso_grid.best_estimator_
best_lasso

Lasso(alpha=10)

In [35]:
lasso_best_predictions = best_lasso.predict(
                            X_test_scaled
)

In [36]:
best_lasso_mse = mean_squared_error(y_test, lasso_best_predictions)
print("Best Lasso Error", best_lasso_mse)

Best Lasso Error 6450131308711.515

## 12. Compare Ridge vs Lasso

In [37]:
comparison = pd.DataFrame({
    'Model ': ['Ridge (Best)', 'Lasso (Best)'],
    'Train Error': [ridge_train_mse, lasso_train_mse],
    'Validation Error' : [best_ridge_mse, best_lasso_mse]
})
print(comparison)

         Model    Train Error  Validation Error
0  Ridge (Best)  6.162303e+12      6.451358e+12
1  Lasso (Best)  6.162284e+12      6.450131e+12

### Interpretation:

> Both Ridge and Lasso models give very similar training and validation errors.
> The validation error is close to training error, which means overfitting is low and the models generalize well.
> Ridge and Lasso perform equally well on this dataset after tuning.

In [38]:
print(

"Number of Features Removed By Lasso =",
sum(lasso_model.coef_==0)

)

Number of Features Removed By Lasso = 0

# PART D: CROSS-VALIDATION STRATEGIES

In [39]:
from sklearn.model_selection import (KFold, StratifiedKFold, LeaveOneOut, TimeSeriesSplit, cross_val_score)

In [40]:
# Use best tuned Ridge model for cross-validation
model = ridge_grid.best_estimator_

### 13. K-Fold Cross-Validation

In [41]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

kfold_scores = cross_val_score(
    model,
    X_train_scaled,
    y_train,
    cv=kfold,
    scoring='neg_mean_squared_error'
)

kfold_mse = -kfold_scores.mean()

print("K-Fold Cross Validation MSE :", kfold_mse)

K-Fold Cross Validation MSE : 6234200179333.175

In [42]:
# Stratified K-Fold Cross-Validation
# Target is binned so StratifiedKFold can balance each fold
y_binned = pd.cut(y_train.reset_index(drop=True), bins=5, labels=False)

stratified_kfold = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

X_train_scaled_reset = X_train_scaled.reset_index(drop=True)

stratified_scores = cross_val_score(
    model,
    X_train_scaled_reset,
    y_train.reset_index(drop=True),
    cv=stratified_kfold.split(X_train_scaled_reset, y_binned),
    scoring='neg_mean_squared_error'
)

stratified_mse = -stratified_scores.mean()

print("Stratified K-Fold MSE :", stratified_mse)

Stratified K-Fold MSE : 6217324392745.735

In [43]:
# Leave-One-Out Cross-Validation (LOOCV)
loo = LeaveOneOut()

loo_scores = cross_val_score(
    model,
    X_train_scaled,
    y_train,
    cv=loo,
    scoring='neg_mean_squared_error'
)

loo_mse = -loo_scores.mean()

print("LOOCV MSE :", loo_mse)

LOOCV MSE : 6215400744245.8

In [44]:
# Time Series Split Cross-Validation
# Pipeline used to prevent data leakage — scaler is fit only on training folds
from sklearn.pipeline import Pipeline

df_sorted = df.sort_values(by='sale_year')

X_time = df_sorted.drop(['house_price_inr', 'property_id'], axis=1)
y_time = df_sorted['house_price_inr']

tscv = TimeSeriesSplit(n_splits=5)

time_pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('ridge', Ridge(alpha=ridge_grid.best_params_['alpha']))
])

time_scores = cross_val_score(
    time_pipe,
    X_time,
    y_time,
    cv=tscv,
    scoring='neg_mean_squared_error'
)

time_mse = -time_scores.mean()

print("Time Series Split MSE :", time_mse)

Time Series Split MSE : 6262924131347.816

### 14. Compare All CV Strategies

In [45]:
cv_results = pd.DataFrame({
    'Cross Validation Method': [
        'K-Fold',
        'Stratified K-Fold',
        'LOOCV',
        'Time Series Split'
    ],
    'MSE Score': [
        kfold_mse,
        stratified_mse,
        loo_mse,
        time_mse
    ]
})

print("\nCross Validation Comparison")
print(cv_results)

Cross Validation Comparison
  Cross Validation Method     MSE Score
0                  K-Fold  6.234200e+12
1       Stratified K-Fold  6.217324e+12
2                   LOOCV  6.215401e+12
3       Time Series Split  6.262924e+12

### Interpretation

> All cross-validation methods produce similar MSE scores, showing stable model performance.\
> K-Fold and Stratified K-Fold give the lowest errors.\
> Time Series Split has a slightly higher error because it respects time order, which is a stricter evaluation.

# PART E: TREE-BASED REGRESSION MODELS

In [46]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error

### 15. Implement Decision Tree Regression

In [47]:
decision_tree = DecisionTreeRegressor(random_state = 42)
decision_tree.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

In [48]:
dt_train_pred = decision_tree.predict(X_train)
dt_test_pred = decision_tree.predict(X_test)

In [49]:
dt_train_mse = mean_squared_error(y_train, dt_train_pred)
dt_test_mse = mean_squared_error(y_test,dt_test_pred) 
dt_r2 = r2_score(y_test, dt_test_pred)

print("Decision Tree Train Error :",dt_train_mse)
print("Decision Tree validation Error :",dt_test_mse)
print("Decision Tree r2 Error :",dt_r2)

Decision Tree Train Error : 0.0
Decision Tree validation Error : 10826810122095.922
Decision Tree r2 Error : 0.8655641974314878

### 16. Control Tree Complexity

In [50]:
decision_tree_tuned = DecisionTreeRegressor(
            max_depth=10,
            min_samples_split=10,
            min_samples_leaf=5,
            random_state=42
)
decision_tree_tuned.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=10, min_samples_leaf=5, min_samples_split=10,
                      random_state=42)

In [51]:
dt_tuned_pred = decision_tree_tuned.predict(X_test)

print("Tuned Tree Error :",mean_squared_error(y_test,dt_tuned_pred))
print("Tuned Tree R2 :",r2_score(y_test,dt_tuned_pred))

Tuned Tree Error : 8725474277219.505
Tuned Tree R2 : 0.8916563490057925

### 17. Implement Random Forest Regression

In [52]:
random_forest = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

# Train Model
random_forest.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [53]:
# Predictions
rf_train_pred = random_forest.predict(X_train)
rf_test_pred = random_forest.predict(X_test)

In [54]:
# Errors
rf_train_mse = mean_squared_error(y_train, rf_train_pred)
rf_test_mse = mean_squared_error(y_test, rf_test_pred)
rf_r2 = r2_score(y_test, rf_test_pred)

print("\nRandom Forest Training Error :", rf_train_mse)
print("Random Forest Validation Error :", rf_test_mse)
print("RF R2 score : ",rf_r2)

Random Forest Training Error : 794868724316.8605
Random Forest Validation Error : 5785958403336.219
RF R2 score :  0.9281561279076027

### 18. Compare Decision Tree vs Random Forest

In [55]:
comparison_df = pd.DataFrame({
    'Model': ['Decision Tree', 'Random Forest'],
    'Training Error': [dt_train_mse, rf_train_mse],
    'Validation Error': [dt_test_mse, rf_test_mse],
    'R2 score': [dt_r2, rf_r2]
})

In [56]:
print("\nSingle Tree vs Ensemble Comparison")
print(comparison_df)

Single Tree vs Ensemble Comparison
           Model  Training Error  Validation Error  R2 score
0  Decision Tree    0.000000e+00      1.082681e+13  0.865564
1  Random Forest    7.948687e+11      5.785958e+12  0.928156

### Interpretation
> Decision Tree overfits — training error is nearly zero but validation error is much higher.\
> Tuning tree depth reduces overfitting.\
> Random Forest performs better because it combines many trees and reduces variance.\
> Higher R2 and lower validation error confirm Random Forest is the stronger model.

# PART F: SUPPORT VECTOR REGRESSION

In [57]:
X_train_svr = X_train_scaled
X_test_svr = X_test_scaled

### 19. Implement SVR with Linear Kernel

In [58]:
from sklearn.svm import SVR
linear_svr = SVR(kernel='linear',C=1)
linear_svr.fit(X_train_svr, y_train)

SVR(C=1, kernel='linear')

In [59]:
linear_train_pred = linear_svr.predict(X_train_svr)
linear_test_pred = linear_svr.predict(X_test_svr)

In [60]:
linear_train_mse = mean_squared_error(y_train, linear_train_pred)
linear_test_mse = mean_squared_error(y_test, linear_test_pred)
linear_r2 = r2_score(y_test, linear_test_pred)

print("Linear SVR Train Error :", linear_train_mse)
print("Linear SVR Validation Error :", linear_test_mse)
print("Linear SVR R2 :", linear_r2)

Linear SVR Train Error : 75040379633796.06
Linear SVR Validation Error : 80689212166031.83
Linear SVR R2 : -0.0019127401175407233

In [61]:
rbf_svr = SVR(kernel='rbf',
             C=100,
             gamma='scale')
rbf_svr.fit(X_train_svr, y_train)

SVR(C=100)

In [62]:
rbf_train_pred = rbf_svr.predict(X_train_svr)
rbf_test_pred = rbf_svr.predict(X_test_svr)

In [63]:
rbf_train_mse = mean_squared_error(y_train, rbf_train_pred)
rbf_test_mse = mean_squared_error(y_test, rbf_test_pred)
rbf_r2 = r2_score(y_test, rbf_test_pred)
print("RBF Train Error :",rbf_train_mse)
print("RBF Validation Error :",rbf_test_mse)
print("RBF R2 :",rbf_r2)

RBF Train Error : 74935038841265.66
RBF Validation Error : 80585694217177.05
RBF R2 : -0.000627364427231214

In [64]:
poly_svr = SVR(
        kernel='poly',
        degree=3,
        C=100
)

In [65]:
poly_svr.fit(
        X_train_svr,
        y_train
)

SVR(C=100, kernel='poly')

In [66]:
poly_pred = poly_svr.predict(X_test_svr)
poly_mse = mean_squared_error(y_test, poly_pred)
poly_r2 = r2_score(y_test, poly_pred)
print("Polynomial Error :",poly_mse)
print("Polynomial R2 :",poly_r2)

Polynomial Error : 80363987434659.67
Polynomial R2 : 0.0021255543832481294

### 20. Hyperparameter Tuning

In [67]:
parameters = {
    'C': [1,10,100],
    'gamma': [0.1, 0.01],
    'kernel': ['rbf']
}

In [68]:
svr_grid = GridSearchCV(
                estimator=SVR(),
                param_grid=parameters,
                cv=5,
                scoring='neg_mean_squared_error'
)
svr_grid.fit(
            X_train_svr,
            y_train
)

GridSearchCV(cv=5, estimator=SVR(),
             param_grid={'C': [1, 10, 100], 'gamma': [0.1, 0.01],
                         'kernel': ['rbf']},
             scoring='neg_mean_squared_error')

In [69]:
print("Best Parameters : ", svr_grid.best_params_)

Best Parameters :  {'C': 100, 'gamma': 0.1, 'kernel': 'rbf'}

In [70]:
best_svr = svr_grid.best_estimator_
best_pred = best_svr.predict(X_test_svr)
best_error = mean_squared_error(y_test, best_pred)
best_r2 = r2_score(y_test, best_pred)
print("Best SVR Error : ",best_error)
print("Best SVR R2 : ",best_r2)

Best SVR Error :  80599940271751.17
Best SVR R2 :  -0.000804256767496625

In [71]:
comparison = pd.DataFrame({
    'Model':[ 'Linear SVR', 'RBF SVR', 'Polynomial SVR'],
    'MSE':[linear_test_mse, rbf_test_mse, poly_mse],
    'R2 Score':[linear_r2, rbf_r2, poly_r2]
})

print(comparison)

            Model           MSE  R2 Score
0      Linear SVR  8.068921e+13 -0.001913
1         RBF SVR  8.058569e+13 -0.000627
2  Polynomial SVR  8.036399e+13  0.002126

## Interpretation:

> All SVR models show high error and low R2 scores, indicating poor performance on this dataset.\
> The reason is that SVR is sensitive to the scale of the target variable. House prices are in crores (very large values), so SVR needs much higher C values or target normalization to work well.\
> Among SVR models, RBF performs slightly better than Linear and Polynomial.

### 21. Compare SVR with Linear and Tree Models

In [72]:
comparison_models = pd.DataFrame({

'Model':['Ridge (Tuned)', 'Lasso (Tuned)', 'Decision Tree', 'Random Forest', 'Best SVR'],
'MSE':[best_ridge_mse, best_lasso_mse, dt_test_mse, rf_test_mse, best_error],
'R2 Score':[r2_score(y_test,best_ridge_predictions), r2_score(y_test,lasso_best_predictions), dt_r2, rf_r2, best_r2]
})

print(comparison_models)

           Model           MSE  R2 Score
0  Ridge (Tuned)  6.451358e+12  0.919894
1  Lasso (Tuned)  6.450131e+12  0.919909
2  Decision Tree  1.082681e+13  0.865564
3  Random Forest  5.785958e+12  0.928156
4       Best SVR  8.059994e+13 -0.000804

### Interpretation
> Random Forest gives the best performance with the highest R2 score and lowest error.\
> Ridge and Lasso (tuned) also perform well and are close to each other.\
> Decision Tree overfits and gives weaker performance.\
> SVR performs poorly on this dataset due to large-scale target values.

# Part G: MODEL COMPARISON & EVALUATION

## 22. Evaluate All Models

In [73]:
import numpy as np
evaluation = pd.DataFrame({

'Model': ['Ridge (Tuned)', 'Lasso (Tuned)', 'Decision Tree', 'Random Forest', 'SVR' ],

'MSE':[ best_ridge_mse, best_lasso_mse, dt_test_mse, rf_test_mse, best_error ],

'MAE':[
    mean_absolute_error(y_test, best_ridge_predictions),
    mean_absolute_error(y_test, lasso_best_predictions),
    mean_absolute_error(y_test, dt_test_pred),
    mean_absolute_error(y_test, rf_test_pred),
    mean_absolute_error(y_test, best_pred)
],

'RMSE':[
np.sqrt(best_ridge_mse),
np.sqrt(best_lasso_mse),
np.sqrt(dt_test_mse),
np.sqrt(rf_test_mse),
np.sqrt(best_error)
],

'R2':[

r2_score(y_test, best_ridge_predictions),
r2_score(y_test, lasso_best_predictions),
dt_r2,
rf_r2,
best_r2
]
})
print(evaluation)

           Model           MSE           MAE          RMSE        R2
0  Ridge (Tuned)  6.451358e+12  1.945385e+06  2.539952e+06  0.919894
1  Lasso (Tuned)  6.450131e+12  1.945520e+06  2.539711e+06  0.919909
2  Decision Tree  1.082681e+13  2.395188e+06  3.290412e+06  0.865564
3  Random Forest  5.785958e+12  1.757755e+06  2.405402e+06  0.928156
4            SVR  8.059994e+13  6.986110e+06  8.977747e+06 -0.000804

# 23. Compare:
- Regularized Linear Models
- Tree-Based Models
- Support Vector Regression

In [74]:
evaluation.sort_values(

        by='R2',

        ascending=False,

        inplace=True

)

print(evaluation)

           Model           MSE           MAE          RMSE        R2
3  Random Forest  5.785958e+12  1.757755e+06  2.405402e+06  0.928156
1  Lasso (Tuned)  6.450131e+12  1.945520e+06  2.539711e+06  0.919909
0  Ridge (Tuned)  6.451358e+12  1.945385e+06  2.539952e+06  0.919894
2  Decision Tree  1.082681e+13  2.395188e+06  3.290412e+06  0.865564
4            SVR  8.059994e+13  6.986110e+06  8.977747e+06 -0.000804

### Interpretation

- Random Forest gives the best performance with highest R2 and lowest errors.
- Ridge and Lasso (tuned) perform well with similar results to each other.
- Decision Tree performs moderately due to overfitting on training data.
- SVR performs poorly because it is not suitable for large-scale target values without target normalization.

### 24. Identify signs of overfitting or underfitting in each model.

**Logic:**

- Train Error << Validation Error → Overfitting
- Train Error ≈ Validation Error → Good Fit
- Both Errors High → Underfitting

In [75]:
models_check = {

'Ridge':[ridge_train_mse, best_ridge_mse],
'Lasso':[lasso_train_mse, best_lasso_mse],
'Decision Tree':[dt_train_mse,dt_test_mse],
'Random Forest':[rf_train_mse,rf_test_mse],
'SVR':[linear_train_mse,best_error]
}

for model_name, errors in models_check.items():
    train = errors[0]
    test = errors[1]
    print("\n", model_name)
    print("Train Error :", train)
    print("Validation Error :", test)

    # Handle edge case: if train error is 0, it is clear overfitting
    if train == 0:
        print("Overfitting (Train error is zero — model memorized training data)")
    elif test > 0 and train < (test * 0.5):
        print("Overfitting")
    elif test > 0 and abs(train - test) / test < 0.15:
        print("Good Fit")
    else:
        print("Underfitting")

 Ridge
Train Error : 6162302702017.451
Validation Error : 6451358176619.913
Good Fit

 Lasso
Train Error : 6162283850258.384
Validation Error : 6450131308711.515
Good Fit

 Decision Tree
Train Error : 0.0
Validation Error : 10826810122095.922
Overfitting (Train error is zero — model memorized training data)

 Random Forest
Train Error : 794868724316.8605
Validation Error : 5785958403336.219
Overfitting

 SVR
Train Error : 75040379633796.06
Validation Error : 80599940271751.17
Good Fit

## Interpretation:

- Ridge and Lasso show good generalization — training and validation errors are very close.
- Decision Tree clearly overfits — training error is zero (memorized all data) but validation error is much higher.
- Random Forest shows slight overfitting but still generalizes well due to bagging.
- SVR shows poor overall performance on this dataset.

# Part H: Final Analysis & Reporting

## 25. Prepare a final report covering:

#### A. Best Performing Model and Justification

In [76]:
best_model = evaluation.sort_values(
                by='R2',
                ascending=False
)
print(best_model.head(1))

           Model           MSE           MAE          RMSE        R2
3  Random Forest  5.785958e+12  1.757755e+06  2.405402e+06  0.928156

### Best Performing Model:

- Random Forest gives the best performance with the highest R2 score and lowest prediction error.
- It combines many decision trees, which reduces variance and avoids overfitting.
- The model produces stable and accurate predictions on unseen data.

#### B. Impact of Regularization

- Regularization helps reduce overfitting by controlling model complexity.
- Ridge reduces coefficient sizes, while Lasso can remove unnecessary features.
- This improves model stability and prediction quality.

#### C. Role of Cross Validation

- Cross-validation helps evaluate model performance on different data splits.
- It reduces dependence on a single train-test split and provides more reliable performance estimates.
- This improves model stability.

#### D. Linear vs Non-Linear Regressors

In [77]:
comparison = pd.DataFrame({

'Category':['Linear Models','Tree Models','SVR'],
'Best Model':['Ridge / Lasso','Random Forest','Best SVR'],
'Performance':['High','Highest','Low']
})
print(comparison)

        Category     Best Model Performance
0  Linear Models  Ridge / Lasso        High
1    Tree Models  Random Forest     Highest
2            SVR       Best SVR         Low

#### E. Business Interpretation

- Accurate house price prediction helps businesses estimate property value more reliably.
- Better predictions improve decision-making for pricing, investments, and market analysis.
- A stable model reduces financial risk.

## Final Conclusion

- Removing the property_id column improved model quality by eliminating a non-predictive feature.
- Regularization improved model stability and reduced overfitting.
- Cross-validation confirmed consistent model performance across different data splits.
- Random Forest is the best model with the highest R2 score and lowest error on test data.
- Ridge and Lasso also performed well and can be used when a simpler, explainable model is needed.
- SVR showed poor results on this dataset due to the large scale of the target variable (house prices in INR).
- Therefore, **Random Forest** is selected as the final model for house price prediction.